{% set name = "simplecosine" %}
{% set version = "1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dedupeio/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 09d2d356ecf5bbaae249f26b30b3128a56899dd6f0d34fbf7ff779a7cd2cd15e

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - numpy
    - python

test:
  source_files:
    - tests
  imports:
    - simplecosine.cosine
  commands:
    - pip check
    - pytest tests -v
  requires:
    - pip
    - pytest

about:
  home: https://github.com/datamade/simplecosine
  summary: Simple cosine distance
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - osamples
